[package]
name = "wi-xilem"
description = "A vi-style node editor — Xilem views"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
petgraph.workspace = true
wi-masonry.workspace = true
xilem.workspace = true

[lints]
workspace = true
