[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["raykast <me@june-s.net>"]
edition = "2024"
repository = "https://github.com/ray-kast/wi"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
accesskit = "0.21.1"
hashbrown = "0.16.0"
indexmap = "2.12.0"
keyboard-types = "0.8.3"
masonry = "0.4.0"
petgraph = "0.8.3"
proc-macro2 = "1.0.103"
quote = "1.0.42"
smallvec = { version = "1.15.1", features = ["const_new"] }
spin = { version = "0.10.0", default-features = false, features = ["once", "spin_mutex"] }
syn = { version = "2.0.109", features = ["extra-traits", "fold", "full"] }
tracing = "0.1.41"
xilem = "0.4.0"

shibari = { version = "0.0.0", path = "crates/shibari", features = ["proc-macros"] }
shibari-grammar = { version = "0.0.0", path = "crates/shibari-grammar" }
shibari-macros = { version = "0.0.0", path = "crates/shibari-macros" }
wi-core = { version = "0.0.0", path = "crates/wi-core" }
wi-macros = { version = "0.0.0", path = "crates/wi-macros" }
wi-masonry = { version = "0.0.0", path = "crates/wi-masonry" }
wi-xilem = { version = "0.0.0", path = "crates/wi-xilem" }

[workspace.lints.rust]
missing_debug_implementations = "deny"
missing_copy_implementations = "deny"
# missing_docs = "warn"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
disallowed_methods = "deny"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
pedantic = { level = "warn", priority = -1 }
style = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
# cargo = { level = "warn", priority = -1 }

[profile.release]
lto = "thin"
strip = true
