[package]
name = "wi-masonry"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
accesskit.workspace = true
masonry.workspace = true
petgraph.workspace = true
smallvec.workspace = true
tracing.workspace = true
wi-core.workspace = true

[lints]
workspace = true
