[package]
name = "wi-core"
description = "A vi-style node editor — framework-agnostic components"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
enum_dispatch = "0.3.13"
keyboard-types.workspace = true
num-traits = "0.2.19"
shibari.workspace = true
shibari.features = ["proc-macros"]
tracing.workspace = true

[lints]
workspace = true
